//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.12 at 10:13:48 PM GMT 
//


package com.actu.backend.users;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.actu.backend.users package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.actu.backend.users
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link GetAllTokensRequest }
     * 
     */
    public GetAllTokensRequest createGetAllTokensRequest() {
        return new GetAllTokensRequest();
    }

    /**
     * Create an instance of {@link GetAllTokensResponse }
     * 
     */
    public GetAllTokensResponse createGetAllTokensResponse() {
        return new GetAllTokensResponse();
    }

    /**
     * Create an instance of {@link TokenList }
     * 
     */
    public TokenList createTokenList() {
        return new TokenList();
    }

    /**
     * Create an instance of {@link GenerateTokenRequest }
     * 
     */
    public GenerateTokenRequest createGenerateTokenRequest() {
        return new GenerateTokenRequest();
    }

    /**
     * Create an instance of {@link GenerateTokenResponse }
     * 
     */
    public GenerateTokenResponse createGenerateTokenResponse() {
        return new GenerateTokenResponse();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link DeleteTokenRequest }
     * 
     */
    public DeleteTokenRequest createDeleteTokenRequest() {
        return new DeleteTokenRequest();
    }

    /**
     * Create an instance of {@link DeleteTokenResponse }
     * 
     */
    public DeleteTokenResponse createDeleteTokenResponse() {
        return new DeleteTokenResponse();
    }

    /**
     * Create an instance of {@link GetTokensByUserRequest }
     * 
     */
    public GetTokensByUserRequest createGetTokensByUserRequest() {
        return new GetTokensByUserRequest();
    }

    /**
     * Create an instance of {@link GetTokensByUserResponse }
     * 
     */
    public GetTokensByUserResponse createGetTokensByUserResponse() {
        return new GetTokensByUserResponse();
    }

    /**
     * Create an instance of {@link ReactivateTokenRequest }
     * 
     */
    public ReactivateTokenRequest createReactivateTokenRequest() {
        return new ReactivateTokenRequest();
    }

    /**
     * Create an instance of {@link ReactivateTokenResponse }
     * 
     */
    public ReactivateTokenResponse createReactivateTokenResponse() {
        return new ReactivateTokenResponse();
    }

    /**
     * Create an instance of {@link RevokeTokenRequest }
     * 
     */
    public RevokeTokenRequest createRevokeTokenRequest() {
        return new RevokeTokenRequest();
    }

    /**
     * Create an instance of {@link RevokeTokenResponse }
     * 
     */
    public RevokeTokenResponse createRevokeTokenResponse() {
        return new RevokeTokenResponse();
    }

    /**
     * Create an instance of {@link GetProfileRequest }
     * 
     */
    public GetProfileRequest createGetProfileRequest() {
        return new GetProfileRequest();
    }

    /**
     * Create an instance of {@link GetProfileResponse }
     * 
     */
    public GetProfileResponse createGetProfileResponse() {
        return new GetProfileResponse();
    }

    /**
     * Create an instance of {@link UpdateProfileRequest }
     * 
     */
    public UpdateProfileRequest createUpdateProfileRequest() {
        return new UpdateProfileRequest();
    }

    /**
     * Create an instance of {@link UpdateProfileResponse }
     * 
     */
    public UpdateProfileResponse createUpdateProfileResponse() {
        return new UpdateProfileResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link AuthUser }
     * 
     */
    public AuthUser createAuthUser() {
        return new AuthUser();
    }

    /**
     * Create an instance of {@link RegisterRequest }
     * 
     */
    public RegisterRequest createRegisterRequest() {
        return new RegisterRequest();
    }

    /**
     * Create an instance of {@link RegisterResponse }
     * 
     */
    public RegisterResponse createRegisterResponse() {
        return new RegisterResponse();
    }

    /**
     * Create an instance of {@link GetCurrentUserRequest }
     * 
     */
    public GetCurrentUserRequest createGetCurrentUserRequest() {
        return new GetCurrentUserRequest();
    }

    /**
     * Create an instance of {@link GetCurrentUserResponse }
     * 
     */
    public GetCurrentUserResponse createGetCurrentUserResponse() {
        return new GetCurrentUserResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

}
