//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.12 at 10:13:48 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://actu.com/users", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.actu.backend.users;
